### ISSUE TITLE
Feature Request: Disable  example files in webinterface

### ISSUE THREAD

**Issue by recretix** [nextcloud/example-files#2]
Hello,

would it be possible to add a checkbox in the webinterface to disable the example files?

Thanks

**Comment by nickvergessen** [comment]
You can set the skeleton directory in your config.
Just set it to an empty folder instead:

https://github.com/nextcloud/server/blob/d26ec44617e5bcda11f5f03a90a35790fc8f6f45/config/config.sample.php#L241-L248
