### ISSUE TITLE
Add templates for Office draw documents

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/example-files#21]

**Comment by juliusknorr** [comment]
@jancborchardt If I remember correctly you also worked on the other templates, right? Do you have any good suggestion on what kind of templates we could add as a default there. I did a quick check on draw.io but the templates all rather seem to be examples and not really something that you can immediately reuse:
<img width="524" alt="Screenshot 2022-02-09 at 17 07 47" src="https://user-images.githubusercontent.com/3404133/153241222-932cf72a-ebc9-4ba4-a1c9-2112e0d3af17.png">
<img width="520" alt="Screenshot 2022-02-09 at 17 07 35" src="https://user-images.githubusercontent.com/3404133/153241232-09b887fd-5f1d-4470-aacf-2a1d1976c208.png">

**Comment by jancborchardt** [comment]
I was thinking it would be fitting to use the same templates we made for Nextcloud Whiteboard, which is an:
- Impact Effort Matrix
- SWOT analysis

Do you think those fit?

Otherwise – are the templates from Draw.io open source? Then I can pick out 3 different ones which we could reuse, might be best?

![Impact Effort Matrix](https://user-images.githubusercontent.com/925062/153862442-0a5b3f6e-ffeb-49b5-a9d7-8520dd42f801.png)
![](https://raw.githubusercontent.com/nextcloud/integration_whiteboard/master/img/screenshot1.jpg)

**Comment by juliusknorr** [comment]
The effort matrix probably, but I think diagrams might be the more suitable suggestion

They are available under the Apache 2.0 license at https://github.com/jgraph/drawio/tree/dev/src/main/webapp/templates

Maybe we can pick some there (you can also browse them directly on draw.io) and adjust them a bit. Exporting as VSDX file and opening them in LibreOffice Draw for adjustments seems to work quite well.

**Comment by jancborchardt** [comment]
Looked through them and here’s the ones I like, and from which category – in order of how I’d sort them in the template list:

### Maps: [Mind map](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/templates/maps/mind_map.xml)
Simple and colorful
![](https://raw.githubusercontent.com/jgraph/drawio/dev/src/main/webapp/templates/maps/mind_map.png)

### Basic: [Flowchart](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/templates/basic/flowchart.xml)
Simple and generic, good as a start
![](https://raw.githubusercontent.com/jgraph/drawio/dev/src/main/webapp/templates/basic/flowchart.png)

### Charts: [Coc org chart](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/templates/charts/coc.xml)
Business-specific
![](https://raw.githubusercontent.com/jgraph/drawio/dev/src/main/webapp/templates/charts/coc.png)

### Business: [Business Model Canvas](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/templates/business/business_model_canvas_1.xml)
Business-specific and professional
![](https://raw.githubusercontent.com/jgraph/drawio/dev/src/main/webapp/templates/business/business_model_canvas_1.png)

-----------

Opinion on the others:
- Venn: Looks nice but seems useless
- Cloud, Engineering, Network, Software, UML, Wireframes, Layout: none, too specific
- Flowcharts: All very complex, basic flowchart is better

What do you think @juliushaertl? :)

**Comment by juliusknorr** [comment]
Makes sense, I've exported them but will need to do some polishing on the styling and elements used, like actually using connector lines instead of simple drawn lines.

**Comment by juliusknorr** [comment]
@jancborchardt @nimishavijay I've exported them and did a few adjustments in terms of the way that they use draw features itself. Could you maybe check if those would be fine from your perspective? https://cloud.nextcloud.com/s/webqF4Gsj3C935W (They are in the shared folder Design > Office > Draw templates if you want to edit them directly)

Once ok with you we can add them here to ship them with the release.

**Comment by juliusknorr** [comment]
Screenshot on how they look in the template picker (we should probably adjust the aspect ratio a bit)
![Screenshot 2022-02-21 at 14 11 14](https://user-images.githubusercontent.com/3404133/154961853-dd88df2d-e0e5-43ae-869d-b0d53a6f5002.png)

**Comment by jancborchardt** [comment]
@juliushaertl finally got around to adjusting the Draw templates! :)
- Mindmap was fine as is
- Flowchart too
- Business model canvas had some typos, and I changed it from the full colored background to just a border around (also nicer if people print it)
- Centered the org chart, removed old-style shadow and used colored border

If we could set the template picker to show the previews in square that would make them look nicer and not cut off? (Except for flowchart, but that’s also fine cause it might be endlessly long)

**Comment by blizzz** [comment]
moving to 25
