### ISSUE TITLE
Request: ability to change example files

### ISSUE THREAD

**Issue by sunjam** [nextcloud/example-files#4]
I’d like to be able to set my own example files on for new users as an admin setting.  This could also help specific releases of Nextcloud such as [NextcloudPi](https://github.com/nextcloud/nextcloudpi) by providing my new users more relevant documentation/pictures/art files.  Thanks!

**Comment by nickvergessen** [comment]
As per https://github.com/nextcloud/example-files/issues/3#issuecomment-365666609

You can set the skeletondirectory to any path you want. The files inside the folder will be copied.
